image: gitpod/workspace-mysql

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      npm install
      jq '
      .bot.token=env.DISCORD_TEST_TOKEN | 
      .dbg_api.service_id="example" | 
      .maria_db={host:"localhost", user:"root", "password": "", database:"vanus_enlightenment", port: 3306} |
      .autostart[0].enabled = false
       ' json/config.json > json/config.json
    command: |
      npm run start


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
